[package]
name = "rune-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Portable runtime request and output contracts for Rune"

[dependencies]
mlua = { version = "0.9.9", default-features = false, features = [
    "lua54",
    "send",
    "vendored",
] }
rustpython-vm = { version = "0.4.0", default-features = false, features = [
    "compiler",
] }
rquickjs = { version = "0.8.1", default-features = false }

[lints]
workspace = true
